repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-yaml
      - id: mixed-line-ending
      - id: requirements-txt-fixer
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files", "--thirdparty", "wandb"]
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.4.0
    hooks:
      - id: nbqa-isort
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
      - id: black-jupyter
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
