[metadata]
name = kirad
version = 0.97.0
license = TBD
copyright = TBD
description = kirad: Kintsugi R&D Utils
url = https://github.com/Kintsugi-Labs/kintsugi-rad
long_description = file: README.md
long_description_content_type = text/markdown
maintainer = Colin Vaz
maintainer_email = colin@kintsugihealth.com
platforms = any
python_requires = ">=3.10"
classifiers =
    Development Status :: 4 - Beta
    Intended Audience :: Science/Research
    Intended Audience :: Healthcare Industry
    License :: Other/Proprietary License
    Operating System :: OS Independent
    Programming Language :: Python
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3.10
    Topic :: Scientific/Engineering
    Topic :: Scientific/Engineering :: Artificial Intelligence
    Topic :: Scientific/Engineering :: Bio-Informatics
    Topic :: Scientific/Engineering :: Medical Science Apps.

[options]
install_requires =
    azure-core>=1.34.0
    azure-identity>=1.22.0
    azure-storage-blob>=12.25.1
    torch>=2.6.0
    loguru>=0.7.3
    numpy>=2.2.6
    pandas>=2.2.3
    peft>=0.15.2
    scipy>=1.15.2
    librosa>=0.11.0
    scikit-learn>=1.1.3
    torchaudio>=2.7.0
    torchmetrics>=1.7.1
    transformers>=4.52.3
    wandb>=0.16.4
    whisper-timestamped>=1.15.8
tests_require =
	pytest
	pytest-cov
	pytest-rerunfailures
	pytest-xdist
include_package_data = True
packages = find:

[options.package_data]
* = *.pt

[options.packages.find]
exclude =
    examples*
    tools*
    docs*
    tests*
    notebooks*
    envs*
    research*

[aliases]
test = pytest

[tool:pytest]
addopts = --cov=kipy --cov-report term --cov-report html:htmlcov
filterwarnings =
	always

[coverage:run]
relative_files = True

[flake8]
max-line-length = 88
extend-ignore = E203
exclude = .eggs
